# YouTube Autopilot Configuration for PastMysteryFiles
# Channel: @pastmysteryfiles-l5g
# Host: Professor Archibald Blackwood

# Language and Localization
language:
  primary: "he"  # Hebrew
  secondary: "en"  # English
  auto_detect: true

# Channel Identity
channel:
  name: "PastMysteryFiles"
  tagline: "Uncovering History's Greatest Mysteries"
  host: "Professor Archibald Blackwood"
  theme: "historical_mysteries"
  target_audience: "history_enthusiasts"

# LLM Configuration
llm:
  provider: "ollama"            # "ollama" | "hf" | "openai"
  model: "qwen2.5:7b-instruct"
  temperature: 0.7
  max_tokens: 1024
  fallback_model: "mistral:7b-instruct"

# Image Generation (Stable Diffusion XL)
sdxl:
  endpoint: "http://localhost:7860"   # או HF endpoint
  model: "stabilityai/stable-diffusion-xl-base-1.0"
  negative_prompt: "low quality, blurry, watermark, text overlay, amateur"
  style_prompt: "professional documentary style, mysterious atmosphere, historical theme, cinematic lighting"
  resolution: "1280x720"
  num_variants: 3

# HeyGen Integration for Shorts
heygen:
  enabled: true
  default_avatar_id: "e0e84faea390465896db75a83be45085"  # Annie - professional look
  default_voice_id: "TBD"  # To be determined after voice testing
  shorts_length: 45  # seconds
  style: "educational_mysterious"

# Whisper Configuration
whisper:
  model_size: "large-v3"
  language: "auto"  # auto-detect
  translate_to_english: true  # for non-Hebrew/English content
  chunk_length: 30  # seconds

# YouTube Settings
youtube:
  default_visibility: "public"
  default_category: "27"  # Education
  default_schedule_cron: "0 9 * * 2,5"  # Tuesday/Friday 09:00 UTC (12:00 Israel)
  shorts_schedule_cron: "0 15 * * *"    # Daily 15:00 UTC (18:00 Israel)
  default_tags: ["history", "mystery", "documentary", "education", "archaeology"]
  
# Content Strategy
content:
  long_form:
    target_length: "8-15 minutes"
    frequency: "twice_weekly"  # Tuesday, Friday
    style: "deep_investigation"
  shorts:
    target_length: "30-60 seconds"
    frequency: "daily"
    style: "quick_facts"
    source: "heygen_avatar"

# Analytics and Monitoring
analytics:
  daily_cron: "0 6 * * *"      # 06:00 UTC daily
  weekly_brief_cron: "0 7 * * 1"  # Monday 07:00 UTC
  metrics_retention_days: 90
  
# Performance Guardrails (KPI thresholds)
guardrails:
  min_ctr: 0.04              # 4% minimum click-through rate
  min_apv: 0.35              # 35% minimum average percentage viewed
  min_subs_per_k: 2          # 2 subscribers per 1000 views
  min_engagement_rate: 0.02   # 2% minimum engagement (likes+comments/views)
  action_on_breach: "open_ticket_and_request_approval"
  consecutive_failures: 2     # Number of consecutive failures before alert

# A/B Testing
experiments:
  ab_titles: true
  ab_thumbs: true
  ab_shorts_avatars: true
  test_duration_hours: 48
  min_sample_size: 100
  confidence_level: 0.95

# Moderation
moderation:
  auto_scan_comments: true
  toxicity_threshold: 0.7
  languages: ["he", "en", "ar"]
  action: "flag_for_review"  # never auto-delete

# Dashboard Configuration
dashboard:
  port: 8501
  auth_required: true
  refresh_interval: 300  # seconds
  theme: "dark"

# Notification Settings
notifications:
  telegram:
    enabled: false
    chat_id: ""
  slack:
    enabled: false
    webhook_url: ""
  email:
    enabled: false
    smtp_server: ""

# Backup and Logging
backup:
  enabled: true
  retention_days: 30
  include_videos: false  # only metadata
  
logging:
  level: "INFO"
  max_file_size: "10MB"
  backup_count: 5


# API Key for YouTube Data API
api_key: "AIzaSyDkwAo5FnewdvDpsEcrnQxOAo6ivZgaoqg"

